{"name": "test_login_01", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_login.TestLogin object at 0x0000000004663588>\n\n    def test_login_01(self):\n        conf = Config()\n        data = Login()\n        test = Assert.Assertions()\n        request = Request.Request()\n    \n        host = conf.host_debug\n        #req_url = \"http://\" + host\n        urls = data.url\n        params = data.data\n        headers = data.header\n    \n        api_url = host + urls[0]\n        response = request.post_request(api_url,params[0],headers[0])\n>       assert test.assert_code(response['code'],300)\n\nTestCase\\test_login.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Common.Assert.Assertions object at 0x0000000004663198>, code = 200\nexpected_code = 300\n\n    def assert_code(self,code,expected_code):\n        \"\"\"\n        验证返回状态吗\n        :param code:\n        :param expected_code:\n        :return:\n        \"\"\"\n        try:\n>           assert code == expected_code\nE           AssertionError\n\nCommon\\Assert.py:21: AssertionError"}, "attachments": [{"name": "log", "source": "c12adad1-0123-4db5-b2d5-eb877e58c07f-attachment.txt", "type": "text/plain"}], "start": 1601201244827, "stop": 1601201245115, "uuid": "26fc0089-499e-4c96-a9fd-f3885e21c0ab", "historyId": "ad46b58c6f38a9e8de6b92b522c7cbff", "testCaseId": "49d28fbbfb79bd9a490d1da4fd8fe957", "fullName": "TestCase.test_login.TestLogin#test_login_01", "labels": [{"name": "story", "value": "Login"}, {"name": "severity", "value": "blocker"}, {"name": "feature", "value": "Home"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "YLMF-1804022100"}, {"name": "thread", "value": "14428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_login"}]}